from pathlib import Path
import sys
REQ={'root': ['SKILL.md', 'README.md', 'VERSION', 'CHANGELOG.md', 'ACCEPTANCE.md'], 'references': ['page-identity-policy.md', 'upstream-artifact-policy.md', 'reuse-policy.md', 'page-type-policy.md', 'section-ownership-policy.md', 'content-binding-policy.md', 'media-binding-policy.md', 'seo-binding-policy.md', 'conversion-binding-policy.md', 'geo-binding-policy.md', 'global-component-policy.md', 'responsive-policy.md', 'accessibility-policy.md', 'wordpress-block-policy.md', 'claim-safety-policy.md', 'approval-policy.md', 'handoff-policy.md', 'verification-policy.md'], 'schemas': ['manifest.schema.json', 'page-identity.schema.json', 'upstream-artifact-register.schema.json', 'page-type.schema.json', 'section-register.schema.json', 'section-source-map.schema.json', 'content-binding.schema.json', 'media-binding.schema.json', 'seo-binding.schema.json', 'conversion-binding.schema.json', 'geo-binding.schema.json', 'global-component-binding.schema.json', 'responsive-binding.schema.json', 'accessibility-check.schema.json', 'wordpress-block-map.schema.json', 'page-assembly-manifest.schema.json', 'assembly-conflict-register.schema.json', 'draft-build-plan.schema.json', 'approval-register.schema.json', 'verification-plan.schema.json', 'cross-skill-handoffs.schema.json', 'closeout.schema.json'], 'templates': ['manifest.yaml', 'page-identity.yaml', 'upstream-artifact-register.yaml', 'page-type.yaml', 'section-register.yaml', 'section-source-map.yaml', 'content-binding.yaml', 'media-binding.yaml', 'seo-binding.yaml', 'conversion-binding.yaml', 'geo-binding.yaml', 'global-component-binding.yaml', 'responsive-binding.yaml', 'accessibility-check.yaml', 'wordpress-block-map.yaml', 'page-assembly-manifest.yaml', 'assembly-conflict-register.yaml', 'draft-build-plan.yaml', 'approval-register.yaml', 'verification-plan.yaml', 'cross-skill-handoffs.yaml', 'closeout.yaml'], 'examples': ['product-detail-assembly', 'seo-article-assembly', 'blocked-assembly']}; r=Path(sys.argv[1]); e=[]
for f in REQ['root']:
    if not (r/f).exists(): e.append('missing:'+f)
for sec in ['references','schemas','templates']:
    for f in REQ[sec]:
        if not (r/sec/f).exists(): e.append('missing '+sec+':'+f)
for d in REQ['examples']:
    if not (r/'examples'/d).is_dir(): e.append('missing example:'+d)
print('PACKAGE_ERRORS='+repr(e)); raise SystemExit(1 if e else 0)
