from pathlib import Path
import sys
REQ={'root': ['SKILL.md', 'README.md', 'VERSION', 'CHANGELOG.md', 'ACCEPTANCE.md'], 'references': ['lifecycle-policy.md', 'environment-policy.md', 'tracking-requirements-policy.md', 'tracking-ownership-policy.md', 'ga4-policy.md', 'gtm-policy.md', 'tag-installation-policy.md', 'event-policy.md', 'conversion-policy.md', 'data-receipt-policy.md', 'gsc-policy.md', 'sitemap-submission-policy.md', 'bing-policy.md', 'indexnow-policy.md', 'search-state-policy.md', 'conflict-policy.md', 'privacy-pii-policy.md', 'approval-policy.md', 'handoff-policy.md', 'verification-policy.md'], 'schemas': ['manifest.schema.json', 'environment-register.schema.json', 'tracking-requirements.schema.json', 'tracking-ownership.schema.json', 'ga4-property.schema.json', 'gtm-container.schema.json', 'tag-installation-register.schema.json', 'event-register.schema.json', 'conversion-register.schema.json', 'event-test-results.schema.json', 'data-receipt-verification.schema.json', 'gsc-property.schema.json', 'gsc-verification.schema.json', 'sitemap-submission.schema.json', 'bing-webmaster.schema.json', 'indexnow-setup.schema.json', 'search-platform-register.schema.json', 'tracking-conflict-register.schema.json', 'privacy-pii-check.schema.json', 'approval-register.schema.json', 'verification-plan.schema.json', 'cross-skill-handoffs.schema.json', 'closeout.schema.json'], 'templates': ['manifest.yaml', 'environment-register.yaml', 'tracking-requirements.yaml', 'tracking-ownership.yaml', 'ga4-property.yaml', 'gtm-container.yaml', 'tag-installation-register.yaml', 'event-register.yaml', 'conversion-register.yaml', 'event-test-results.yaml', 'data-receipt-verification.yaml', 'gsc-property.yaml', 'gsc-verification.yaml', 'sitemap-submission.yaml', 'bing-webmaster.yaml', 'indexnow-setup.yaml', 'search-platform-register.yaml', 'tracking-conflict-register.yaml', 'privacy-pii-check.yaml', 'approval-register.yaml', 'verification-plan.yaml', 'cross-skill-handoffs.yaml', 'closeout.yaml'], 'examples': ['new-site-verified', 'gtm-owned-setup', 'blocked-duplicate-pii']}; r=Path(sys.argv[1]); e=[]
for f in REQ['root']:
    if not (r/f).exists(): e.append('missing:'+f)
for sec in ['references','schemas','templates']:
    for f in REQ[sec]:
        if not (r/sec/f).exists(): e.append('missing '+sec+':'+f)
for d in REQ['examples']:
    if not (r/'examples'/d).is_dir(): e.append('missing example:'+d)
print('PACKAGE_ERRORS='+repr(e)); raise SystemExit(1 if e else 0)
