from pathlib import Path
import sys
REQ={'root': ['SKILL.md', 'README.md', 'VERSION', 'CHANGELOG.md', 'ACCEPTANCE.md'], 'references': ['state-machine-policy.md', 'wb07-readiness-policy.md', 'scope-policy.md', 'manifest-policy.md', 'strategy-policy.md', 'predeployment-policy.md', 'snapshot-policy.md', 'rollback-policy.md', 'approval-policy.md', 'execution-policy.md', 'smoke-test-policy.md', 'production-verification-policy.md', 'technical-seo-policy.md', 'tracking-policy.md', 'form-email-policy.md', 'incident-policy.md', 'search-handoff-policy.md', 'indexing-boundary-policy.md', 'ranking-boundary-policy.md', 'evidence-policy.md', 'change-control-policy.md', 'handoff-policy.md', 'verification-policy.md'], 'schemas': ['manifest.schema.json', 'launch-context.schema.json', 'wb07-readiness.schema.json', 'deployment-scope.schema.json', 'deployment-manifest.schema.json', 'deployment-strategy.schema.json', 'pre-deployment-check.schema.json', 'snapshot-register.schema.json', 'rollback-plan.schema.json', 'approval-register.schema.json', 'deployment-execution.schema.json', 'smoke-test.schema.json', 'production-verification.schema.json', 'rollback-execution.schema.json', 'rollback-verification.schema.json', 'launch-incident-register.schema.json', 'search-handoff.schema.json', 'indexing-handoff.schema.json', 'launch-gate.schema.json', 'verification-plan.schema.json', 'cross-skill-handoffs.schema.json', 'closeout.schema.json'], 'templates': ['manifest.yaml', 'launch-context.yaml', 'wb07-readiness.yaml', 'deployment-scope.yaml', 'deployment-manifest.yaml', 'deployment-strategy.yaml', 'pre-deployment-check.yaml', 'snapshot-register.yaml', 'rollback-plan.yaml', 'approval-register.yaml', 'deployment-execution.yaml', 'smoke-test.yaml', 'production-verification.yaml', 'rollback-execution.yaml', 'rollback-verification.yaml', 'launch-incident-register.yaml', 'search-handoff.yaml', 'indexing-handoff.yaml', 'launch-gate.yaml', 'verification-plan.yaml', 'cross-skill-handoffs.yaml', 'closeout.yaml'], 'examples': ['successful-full-site-launch', 'approved-page-only-deployment', 'rolled-back-blocked-launch']};r=Path(sys.argv[1]);e=[]
for f in REQ['root']:
 if not (r/f).exists():e.append('missing:'+f)
for sec in ['references','schemas','templates']:
 for f in REQ[sec]:
  if not (r/sec/f).exists():e.append('missing '+sec+':'+f)
for d in REQ['examples']:
 if not (r/'examples'/d).is_dir():e.append('missing example:'+d)
print('PACKAGE_ERRORS='+repr(e));raise SystemExit(1 if e else 0)
