from pathlib import Path
import sys
REQ={'root': ['SKILL.md', 'README.md', 'VERSION', 'CHANGELOG.md', 'ACCEPTANCE.md'], 'references': ['evidence-policy.md', 'upstream-readiness-policy.md', 'sampling-policy.md', 'severity-policy.md', 'page-completeness-policy.md', 'responsive-policy.md', 'navigation-policy.md', 'form-policy.md', 'email-policy.md', 'conversion-policy.md', 'technical-seo-policy.md', 'tracking-search-policy.md', 'infrastructure-policy.md', 'performance-policy.md', 'accessibility-policy.md', 'browser-policy.md', 'defect-policy.md', 'retest-policy.md', 'risk-acceptance-policy.md', 'launch-gate-policy.md', 'approval-policy.md', 'handoff-policy.md', 'verification-policy.md'], 'schemas': ['manifest.schema.json', 'prelaunch-context.schema.json', 'upstream-readiness.schema.json', 'page-sample-plan.schema.json', 'page-completeness-check.schema.json', 'responsive-check.schema.json', 'navigation-check.schema.json', 'form-check.schema.json', 'email-delivery-check.schema.json', 'conversion-path-check.schema.json', 'technical-seo-check.schema.json', 'tracking-check.schema.json', 'search-readiness-check.schema.json', 'infrastructure-check.schema.json', 'performance-check.schema.json', 'accessibility-check.schema.json', 'browser-check.schema.json', 'defect-register.schema.json', 'retest-register.schema.json', 'risk-acceptance-register.schema.json', 'launch-gate.schema.json', 'approval-register.schema.json', 'verification-plan.schema.json', 'cross-skill-handoffs.schema.json', 'closeout.schema.json'], 'templates': ['manifest.yaml', 'prelaunch-context.yaml', 'upstream-readiness.yaml', 'page-sample-plan.yaml', 'page-completeness-check.yaml', 'responsive-check.yaml', 'navigation-check.yaml', 'form-check.yaml', 'email-delivery-check.yaml', 'conversion-path-check.yaml', 'technical-seo-check.yaml', 'tracking-check.yaml', 'search-readiness-check.yaml', 'infrastructure-check.yaml', 'performance-check.yaml', 'accessibility-check.yaml', 'browser-check.yaml', 'defect-register.yaml', 'retest-register.yaml', 'risk-acceptance-register.yaml', 'launch-gate.yaml', 'approval-register.yaml', 'verification-plan.yaml', 'cross-skill-handoffs.yaml', 'closeout.yaml'], 'examples': ['ready-industrial-site', 'accepted-risk-site', 'blocked-launch']};r=Path(sys.argv[1]);e=[]
for f in REQ['root']:
 if not (r/f).exists():e.append('missing:'+f)
for sec in ['references','schemas','templates']:
 for f in REQ[sec]:
  if not (r/sec/f).exists():e.append('missing '+sec+':'+f)
for d in REQ['examples']:
 if not (r/'examples'/d).is_dir():e.append('missing example:'+d)
print('PACKAGE_ERRORS='+repr(e));raise SystemExit(1 if e else 0)
